# App_Ventas
Proyectos desarrollados en Netbeans
package Ventas;

import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class Principal_Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Principal_Ventas
     */
    String Totales [] = new String [1];
    String Total [] = new String [1];
    
    public Principal_Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jrbModelo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jrbPentium = new javax.swing.JRadioButton();
        jrbAMD = new javax.swing.JRadioButton();
        jrbAthlon = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jcbDisco = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jcbPantalla = new javax.swing.JComboBox();
        jbtCalcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtImprimir = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Modelo");

        jrbModelo.add(jrbPentium);
        jrbPentium.setText("Pentium V");
        jrbPentium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPentiumActionPerformed(evt);
            }
        });

        jrbModelo.add(jrbAMD);
        jrbAMD.setText("AMD Duron");

        jrbModelo.add(jrbAthlon);
        jrbAthlon.setText("Athlon");

        jLabel2.setText("Disco duro");

        jcbDisco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "80", "120", "160", "200" }));

        jLabel3.setText("Pantalla");

        jcbPantalla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sin Pantalla", "Pantalla 14", "Pantalla 15", "Pantalla 17", "Pantalla 19", "Sobre    19 " }));

        jbtCalcular.setText("Calcular");
        jbtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCalcularActionPerformed(evt);
            }
        });

        jLabel4.setText("GB");

        jLabel5.setText("Pulg.");

        jbtImprimir.setText("Imprimir");
        jbtImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtImprimirActionPerformed(evt);
            }
        });

        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        jLabel6.setText("Total");

        jtxtTotal.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbPentium)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jrbAthlon)
                                .addComponent(jrbAMD)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtCalcular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbDisco, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbPantalla, javax.swing.GroupLayout.Alignment.LEADING, 0, 103, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jrbPentium)
                    .addComponent(jLabel2)
                    .addComponent(jcbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbAMD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbAthlon)
                    .addComponent(jLabel3)
                    .addComponent(jcbPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jbtCalcular)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtImprimir)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jbtSalir)
                        .addContainerGap(55, Short.MAX_VALUE))))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-430)/2, (screenSize.height-339)/2, 430, 339);
    }// </editor-fold>                        

    public void pedido (){
    
        int Total = 0;
        
        if (jrbPentium.isSelected())
        {
           Total+=300000;
        }
        else{
        
            if (jrbAMD.isSelected())
        {
            Total+=270000;
        }
            else {
          if (jrbAthlon.isSelected())
        {
           Total+=250000;
        }
            }
        
        }
        
        int Disco=jcbDisco.getSelectedIndex();
        switch (Disco) {
        
            case 0: Total +=44000;
                break;
            case 1: Total +=60000;
                break;
            case 2: Total +=89000;
                break;
            case 3: Total +=122000;
               
        }
        int Pantalla = jcbPantalla.getSelectedIndex();
        switch (Pantalla){
        
            case 1: Total+= 50000;
                break;
            case 2: Total+=66000;
                break;
            case 3: Total+=85000;
                break;
            case 4: Total+=125000;
                break;
            case 5: Total+=140000;
                
        
        }
        
        double Resultado = Total*1.19 ;
        
        JOptionPane.showMessageDialog(null,"A Pagar: $"+Resultado);
        jtxtTotal.setText(""+Resultado);
        
        
    
    }
    private void jrbPentiumActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        System.exit (0);
        
    }                                        

    private void jbtCalcularActionPerformed(java.awt.event.ActionEvent evt) {                                            
    pedido ();
    
   Totales [1] = jtxtTotal.getText();
    
    // TODO add your handling code here:
    
    }                                           

    private void jbtImprimirActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        
   JOptionPane.showMessageDialog(null,"A Pagar con IVA: $"+Totales);        
        
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal_Ventas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtCalcular;
    private javax.swing.JButton jbtImprimir;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JComboBox jcbDisco;
    private javax.swing.JComboBox jcbPantalla;
    private javax.swing.JRadioButton jrbAMD;
    private javax.swing.JRadioButton jrbAthlon;
    private javax.swing.ButtonGroup jrbModelo;
    private javax.swing.JRadioButton jrbPentium;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration                   
}
